#!/usr/bin/env bash

shopt -s dotglob

GLOBIGNORE="*.DS_Store*:.git/*:Windows*:README*"
REPO=$HOME/Documents/dotfiles
HOMEBAKUP="$HOME/.oldotfiles"


if [[ "$1" != "install" ]] && [[ "$1" != "uninstall" ]]; then
    echo "usage: $0 [install | uninstall]"
    exit 1
fi

################################################################
# INSTALL

if [[ "$1" == "install" ]]; then

    if [[ -d "$HOMEBAKUP" ]]; then
        echo "$HOMEBAKUP already exists, please sort this manually"
        exit 1
    fi

    echo mkdir -p "$HOMEBAKUP"                                                   #echo

    cd $REPO || { echo "could not cd into $REPO" && exit 2; }

    for i in *; do
        # echo $i
        if [[ -e "$HOME/$i" ]]; then
            echo cp -r "$HOME/$i" "$HOMEBAKUP"                                   #echo
            echo cp -r "$i" "$HOME"                                              #echo
        fi
    done

fi

################################################################
# UNINSTALL

if [[ "$1" == "uninstall" ]]; then

    if ! [[ -d "$HOMEBAKUP" ]]; then
        echo "no $HOMEBAKUP, nothing to restore"
        exit 1
    fi

    cd $REPO || { echo "could not cd into $REPO" && exit 2; }

    for i in *; do
        # echo $i
        if [[ -e "$HOME/$i" ]]; then
            echo rm -r "$i"                                                  #echo
        fi
    done

    echo mv "$HOMEBAKUP"/* ~                                                 #echo
    echo rmdir "$HOMEBAKUP"                                                  #echo

fi
