#!/bin/bash
#print all executables in PATH
ifsold=$IFS
IFS=:   

for folder in $PATH
do  
	echo "$folder:"
	for file in $folder/*
	do  
		if [ -x $file ] 
		then
			echo "  $file"
		fi  
	done
done
IFS=$ifsold
