#!/bin/bash

shopt -s nullglob

today="$(date +%y%m%d)"

loc="$PWD"
cd ~ || exit 1

everything=(
    .bin/
    .bashrc
    .profile
    .bash_profile
    .zshrc
    .vimrc
    .bash_logout
    .inputrc
    .Xdefaults
    .hammerspoon/
    .emacs.d/{init.el,lisp/}
    .newsboat/{,yt}{config,urls}
    .config/{karabiner/,i3/{config,status.conf,xinit}}
    TEXTFILES

    Accumulator/
    Code/
    Desktop/
    Documents/
    Downloads/
    Movies/
    Music/
    Pictures/
    Projects/
)

ACTUAL_UPDATE=()

for the_file in "${everything[@]}"; do
    if [[ -e "$the_file" ]]; then
        ACTUAL_UPDATE+=("$the_file")
    fi
done

tar czvf "${loc}/bup--${today}.tgz" "${ACTUAL_UPDATE[@]}"
