#!/usr/bin/env bash

shopt -s dotglob

export GLOBIGNORE="*.DS_Store*:.git/*:Windows*:README*"
REPO="$HOME/Documents/dotfiles"
HOMEBAKUP="$HOME/.oldotfiles"

if [[ $# != 1 ]] || [[ "$1" != "install" ]] && [[ "$1" != "uninstall" ]]; then
    echo "usage: ${0##*/} [install | uninstall]"
    exit 1
fi

read -p "please be sure of what you want"

################################################################
# INSTALL

if [[ "$1" == "install" ]]; then

    if [[ -d "$HOMEBAKUP" ]]; then
        echo "$HOMEBAKUP already exists, please sort this manually"
        exit 1
    fi

    cd "$REPO" || { echo "could not cd into $REPO" && exit 2; }
    mkdir -p "$HOMEBAKUP"

    for i in *; do
        if [[ -e "$HOME/$i" ]]; then
            echo cp -r "$HOME/$i" "$HOMEBAKUP"
            cp -r "$HOME/$i" "$HOMEBAKUP"
        fi
        echo cp -r "$i" "$HOME"
        cp -r "$i" "$HOME"
    done

fi

################################################################
# UNINSTALL

if [[ "$1" == "uninstall" ]]; then

    if ! [[ -d "$HOMEBAKUP" ]]; then
        echo "no $HOMEBAKUP, nothing to restore"
        exit 1
    fi

    cd "$REPO" || { echo "could not cd into $REPO" && exit 2; }

    for i in *; do
        if [[ -e "$HOME/$i" ]]; then
            echo rm -rf "$HOME/$i"
            rm -rf "$HOME/${i:?}"
        fi
    done

    echo mv "$HOMEBAKUP"/* ~
    mv "$HOMEBAKUP"/* ~
    echo rmdir "$HOMEBAKUP"
    rmdir "$HOMEBAKUP"
fi
