#!/bin/bash

if [[ $# -eq 0 ]]; then
cat << END
  usage:
    -- hit get whateva
    -- hit put 'some/where' updateReq.json
    -- hit post some/where '{"straight":"data"}'
END
exit
fi

user='theUser'
pass='thePassword'
base="http://127.0.0.1:8080"
endpoint="$2"
url="${base}/${endpoint}"
data="$3"
log="$HOME/bin/testrest/logs/${1}--${endpoint//\//_}--$(date +%H%M%S).txt"

if [[ ! "$data" ]]; then
    :
elif [[ -f "$data" ]]; then
    data="--body-file=${data}"
else
    data="--body-data=${data}"
fi

wget -O- --content-on-error=on --user="$user" --password="$pass" \
    --header='Accept:application/json' --header='Content-Type:application/json' \
    --method="${1^^}" "$url" "$data" -o "$log" | tee -a "$log"

wcode=$?
if [[ $wcode -gt 1 ]]; then
    echo -e "\n" >&2
    echo "wget returned $wcode" >&2
    cat "$log" >&2
    exit $wcode
fi

