#!/usr/bin/env bash

dotfiles="$HOME/Documents/dotfiles"

cd $dotfiles || exit 1
printf "\n\nopen/continue/abort? (Return/Space/Ctrl-C)\n\n"
for gdotfile in $(git ls-files); do
    homedotfile="$HOME/$gdotfile"
    if [[ -f "$homedotfile" ]] &&
           ! diff "$homedotfile" "$gdotfile" &>/dev/null; then
        echo "$gdotfile $homedotfile"
        read -s -n1
        if [[ "$REPLY" == " " ]]; then continue
        else
            emacs -Q --eval "(ediff-files \"$homedotfile\" \"$gdotfile\")" 2>/dev/null;
        fi
    fi
done
echo

