#!/usr/bin/env bash

dotfiles="$HOME/Documents/dotfiles"

cd $dotfiles || exit 1
local_dotfiles=()
remote_dotfiles=()
for gdotfile in $(git ls-files); do
    homedotfile="$HOME/$gdotfile"
    if [[ -f "$homedotfile" ]] &&
           ! diff "$homedotfile" "$gdotfile" &>/dev/null; then
        local_dotfiles+=("$homedotfile")
        remote_dotfiles+=("$gdotfile")
    fi
done

for menu in $(seq "${#local_dotfiles[@]}"); do
    echo $((menu - 1)) ${remote_dotfiles[$((menu - 1))]}
done

echo
echo "enter index"
while true; do
    read idx
    if [[ ! "$idx" =~ ^[[:digit:]]+$ ]]; then exit 1; fi
    emacs -Q -nw --eval "(progn (load-theme 'whiteboard) (ediff-files \"${local_dotfiles[$idx]}\" \"${remote_dotfiles[$idx]}\" '(ediff-toggle-split)))" 2>/dev/null;
done
echo
