#!/bin/bash

## usage:
## -- qu db-yo scr.sql
## -- qu db-whaat "select * from lm;"

schema="$1"
query="$2"

# credentials can be inserted in a safer way
if [[ -f "$query" ]]; then
	mysql -uroot -pXXXX -B --skip-column-names -D "$schema" < "$query" 2>/dev/null 
else
	mysql -uroot -pXXXX -B --skip-column-names -D "$schema" -e "$query" 2>/dev/null 
fi

