#!/bin/bash

if [[ $# -eq 0 ]]; then
cat << END
   usage:
     -- qu db-whaat scr.sql
     -- qu db-yo "select * from lm;"
END
exit
fi

user='theUser'
pass='thePassword'
schema="$1"
query="$2"

if [[ -f "$query" ]]; then
	mysql -u"$user" -p"$pass" \
              -B --skip-column-names \
              -D "$schema" < "$query" 2>/dev/null
else
	mysql -u"$user" -p"$pass" \
              -B --skip-column-names \
              -D "$schema" -e "$query" 2>/dev/null
fi

