#!/usr/bin/env python3

import random

keys=['a','b','c','d','e','f','g',
      random.choice(['g#','ab']),
      random.choice(['a#','bb']),
      random.choice(['c#','db']),
      random.choice(['d#','eb']),
      random.choice(['f#','gb'])]

random.shuffle(keys)
for i,j in enumerate(keys):
    print(j+"\t", end="")
    if (i+1) % 4 == 0:
        print()


