#!/usr/bin/env python

import random

def tabulatekeys():
    keys=['a','b','c','d','e','f','g','ab','bb','c#','eb', 'f#']
    random.shuffle(keys)
    for i,j in enumerate(keys):
        print(j+"\t", end="")
        if (i+1) % 4 == 0:
            print()

tabulatekeys()

